(define (make-leaf symbol weight)
  (list 'leaf symbol weight))
(define (leaf? object)
  (eq? (car object) 'leaf))
(define (symbol-leaf x) (cadr x))
(define (weight-leaf x) (caddr x))
(define (make-code-tree left right)
  (list left
        right
        (append (symbols left) (symbols right))
        (+ (weight left) (weight right))))

(define (left-branch tree) (car tree))
(define (right-branch tree) (cadr tree))
(define (symbols tree)
  (if (leaf? tree)
      (list (symbol-leaf tree))
      (caddr tree)))
(define (weight tree)
  (if (leaf? tree)
      (weight-leaf tree)
      (cadddr tree)))
(define (decode bits tree)
  (define (decode-1 bits current-branch)
    (if (null? bits)
        '()
        (let ((next-branch
               (choose-branch (car bits) current-branch)))
          (if (leaf? next-branch)
              (cons (symbol-leaf next-branch)
                    (decode-1 (cdr bits) tree))
              (decode-1 (cdr bits) next-branch)))))
  (decode-1 bits tree))
(define (choose-branch bit branch)
  (cond ((= bit 0) (left-branch branch))
        ((= bit 1) (right-branch branch))
        (else (error "bat bit -- CHOOSE BRANCH" bit))))

(define sample-tree
  (make-code-tree (make-leaf 'A 4)
                  (make-code-tree
                   (make-leaf 'B 2)
                   (make-code-tree (make-leaf 'D 1)
                                   (make-leaf 'C 1)))))
;; => ((leaf A 4) ((leaf B 2) ((leaf D 1) (leaf C 1) (D C) 2) (B D C) 4) (A B D C) 8)
((leaf A 4)
 ((leaf B 2)
  ((leaf D 1)
   (leaf C 1)
   (D C) 2)
  (B D C) 4)
 (A B D C) 8)

(define sample-message '(0 1 1 0 0 1 0 1 0 1 1 1 0))

(define (element-of-set? x set)
  (cond ((null? set) #f)
        ((equal? x (car set)) #t)
        (else (element-of-set? x (cdr set)))))

(define (encode message tree)
  (if (null? message)
      '()
      (append (encode-symbol (car message) tree)
              (encode (cdr message) tree))))
(define (encode-symbol symbol tree)
  (if (leaf? tree)
      '()
      (let ((left-tree (left-branch tree))
            (right-tree (right-branch tree)))
        (cond ((element-of-set? symbol (symbols left-tree))
               (cons '0 (encode-symbol symbol left-tree)))
              ((element-of-set? symbol (symbols right-tree))
               (cons '1 (encode-symbol symbol right-tree)))
              (else (error "not found -- ENCODE SYMBOL" symbol))))))

(encode '(A D A B B C A) sample-tree) ;; => (0 1 1 0 0 1 0 1 0 1 1 1 0)
(equal? sample-message '(0 1 1 0 0 1 0 1 0 1 1 1 0)) ;; => #t